### ISSUE TITLE
Implement status check in Client calls to the Server

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-auth#17] opened 2020-01-30 09:48 UTC
Currently Client [makes a call](https://github.com/Holo-Host/holo-auth/blob/develop/client/src/main.rs#L43) to Holo-Auth Server in a happy mode. Accounting for edge cases will improve reliability of the service.

Possible failures (networking timeout, Postmart failure) could result in a retry.

**Comment by yegortimoshenko** [comment] 2020-01-30 10:16
Duplicate of #16.

**Closed by yegortimoshenko** 2020-01-30 10:16 UTC
Labels: enhancement
